# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool: 
   name: Default
#  vmImage: 'windows-latest'

jobs:
- job: Nuke
  displayName: Nuke
  workspace:
    clean: all
  steps: 
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 3.1'
      inputs: 
        packageType: sdk
        useGlobalJson: true
        includePreviewVersions: true
        installationPath: $(Agent.ToolsDirectory)
#

    - task: PowerShell@2
      inputs:
        displayName: 'Nuke Build'
        filePath: '$(Build.SourcesDirectory)/build.ps1'
        arguments: '--target distbuild'
        workingDirectory: '$(Build.SourcesDirectory)'